# Etude des données du fichier excel

langchain

In [1]:
import os
from pathlib import Path
import pandas as pd
import numpy as np
import json

In [2]:
file = Path("/home/sachard/mairie/data/clean_extracts/seed_data_20260420_105546.json")
data = json.loads(file.read_text(encoding="utf-8"))
df = pd.DataFrame(data)  # Remplacez "inventaire"
display(df)

,SERVICE,EMPLACEMENT,UTILISATEUR PRINCIPAL,NOM RESEAU,N° SERIE PC,CLEF WIFI,LECTEUR DVD/CD EXTERNE,WEBCAM,CASQUE,TYPE,...,DATE ACHAT ECRAN TELETRAVAIL,DATE FIN GARANTIE ECRAN TELETRAVAIL,TYPE ECRAN TELETRAVAIL2,MARQUE ECRAN TELETRAVAIL3,MODELE ECRAN TELETRAVAIL4,N° SERIE ECRAN TELETRAVAIL5,FOURNISSEUR ECRAN TELETRAVAIL6,N° BC ECRAN TELETRAVAIL7,DATE ACHAT ECRAN TELETRAVAIL8,DATE FIN GARANTIE ECRAN TELETRAVAIL2
0,?????????,?????????,None,None,None,None,None,None,None,ECRAN,...,None,None,None,None,None,None,NaN,None,None,None
1,?????????,?????????,None,None,None,None,None,None,None,ECRAN,...,None,None,None,None,None,None,NaN,None,None,None
2,?????????,?????????,None,None,None,None,None,None,None,ECRAN,...,None,None,None,None,None,None,NaN,None,None,None
3,?????????,?????????,None,None,None,None,None,None,None,ECRAN,...,None,None,None,None,None,None,NaN,None,None,None
4,?????????,?????????,None,None,None,None,None,None,None,ECRAN,...,None,None,None,None,None,None,NaN,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
665,STOCK PC,DSI,None,None,JN22WF4,None,None,None,None,PC PORTABLE,...,None,None,None,None,None,None,NaN,None,None,None
666,STOCK PC,DSI,None,None,FN22WF4,None,None,None,None,PC PORTABLE,...,None,None,None,None,None,None,NaN,None,None,None
667,STOCK PC,DSI,None,None,HN22WF4,None,None,None,None,PC PORTABLE,...,None,None,None,None,None,None,NaN,None,None,None
668,STOCK PC,DSI,None,None,H4W1WF4,None,None,None,None,PC PORTABLE,...,None,None,None,None,None,None,NaN,None,None,None
669,STOCK PC,DSI,None,None,G4W1WF4,None,None,None,None,PC PORTABLE,...,None,None,None,None,None,None,NaN,None,None,None

In [3]:
df.describe(include="all")

,SERVICE,EMPLACEMENT,UTILISATEUR PRINCIPAL,NOM RESEAU,N° SERIE PC,CLEF WIFI,LECTEUR DVD/CD EXTERNE,WEBCAM,CASQUE,TYPE,...,DATE ACHAT ECRAN TELETRAVAIL,DATE FIN GARANTIE ECRAN TELETRAVAIL,TYPE ECRAN TELETRAVAIL2,MARQUE ECRAN TELETRAVAIL3,MODELE ECRAN TELETRAVAIL4,N° SERIE ECRAN TELETRAVAIL5,FOURNISSEUR ECRAN TELETRAVAIL6,N° BC ECRAN TELETRAVAIL7,DATE ACHAT ECRAN TELETRAVAIL8,DATE FIN GARANTIE ECRAN TELETRAVAIL2
count,670,665,530,487,515,4,16,26,29,628,...,1,1,1,1,1,1,1.0,1,1,0
unique,69,121,359,452,509,3,1,13,12,24,...,1,1,1,1,1,1,NaN,1,1,0
top,STOCK ECRAN,DSI,FOND DE CLASSE,LINUX,8YCL7S3,INTEGRE,OUI 22/11/2023,OUI,OUI,PC FIXE,...,2024-07-17 00:00:00,2029-07-16 00:00:00,DELL,DELL 27 - P2724DEB,8362K04,DELL,NaN,2024-07-31 00:00:00,2029-07-30 00:00:00,NaN
freq,129,204,25,24,2,2,16,12,14,180,...,1,1,1,1,1,1,NaN,1,1,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,32240163.0,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,32240163.0,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,32240163.0,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,32240163.0,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,32240163.0,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,32240163.0,NaN,NaN,NaN

In [20]:
col = "PROCESSEUR PC"  # ← change ce nom pour naviguer
print(f"=== {col} ===")
for val in df[col].dropna().unique():
    print(val)

=== PROCESSEUR PC ===
Intel(R) Core(TM) i5-10500 (6 Cores/12MB/12T/3.1GHz to 4.5GHz/65W)
Intel® Core™ i5-1235U de 12e génération (10 cœurs - 4,40 GHz)
Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
Intel(R) Core(TM) i5-9500
12th Generation Intel Core i5-12500T
Intel Core i5-4590 3,3 Ghz
I5-1135G7
11th Generation Intel Core i5-1135G7
Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz
Intel®Core™ i7-1250U (12Mo Cache, jusqu’à 4,7 GHz, 10 Coeurs)
Intel(R) Core(TM) i5-10505 CPU @ 3.20GHz
Intel I5 - 512 GB SSD
Intel Core i5-10505 (6 coeurs/12Mo/12T/de 3,2GHz à 4,6GHz/65W)
Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
Intel® Core™ Ultra 5 235U vPro™ (12 TOPS NPU, 12 coeurs, 4,9 GHz)
Intel® Core™ Ultra 7 255H (24Mo, 16 Coeurs, 5,10GHz Turbo, 45W)
Processeur Intel Core Ultra 7 155H, vPro Essentials (24 mo 16 CŒURS)
Core 2 DUO P7350@2Ghz
i7-2670QM
i5-6200U
Intel Core i5-8250U
Intel i5-1135G7
Intel® Core™ Ultra 5 125U processeur - 12 Cœurs - 4,3 GHz
Intel i5-1135G7, Intel Iris Xe Graphics Capable
Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
Processeur Intel Core i5-1335U (10 coeurs, jusqu’à 4,6 GHz Turbo)
i7-4770 3.40GHz
Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Processeur Intel Core i5-12500T (6 coeurs/18 Mo/12T/2 GHz à 4,4 GHz)
11th Gen Intel(R) Core(TM) i5-11600K @ 3.90GHz
I5-6500 3,2GHz
Intel(R) Core(TM) i5-8500 CPU @ 3.00GH
 Intel Core i5-1345U de 13e génération
11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
processeur Intel i5-1135G7
i5 i5-4440@3,10Ghz
i5-10210U CPU @ 1.60GHz
12th Generation Intel Core i5-12500
Intel Core i5 14500 vPro (14 cœurs - 5 GHz)
Intel  core I5-6500 3,20GHz
Intel core I3 6100 3,7GHz
Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz
DUALCORE 2,60Ghz
Intel Core i5-6500 3,2Ghz
i5-2400 @3,10GHz
I5-2400 3,1ghZ
i5-1245U
Processeur Intel® Core™ i5-12500T de 12e génération (cache 18 Mo,
6 coeurs, 12 threads, jusqu‘à 4,4 GHz Turbo, 35 W)
Ii5-6600 3,3GHz
Processeur Intel Core i5-12500 (6 coeurs/3,0 GHz/4,6 GHz)
Intel Core i5-12500 (6 Cores/18MB/12T/65W)
Intel Core i5-6500 3,2GHz
i3-4130 @3,40GHz
Core I5 M480 2,67Ghz
Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
Intel Core i5-12500T (6 cœurs-4,4 GHz)
Core 2 Duo T8300 @2,40Ghz
Core I7-6700HQ
Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
 i7-7770 @3,60Ghz
i5-7300HQ
Processeur Intel® Core™ i5-14500T vPro® (cache 24 Mo, 14 coeurs, 20 threads, jusqu‘à 4,8 GHz)
Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
Intel Core i3
Intel® Core™ Ultra 5 235T (R) (13 TOPS NPU, 14 coeurs, jusqu’à 5,0 GHz)
Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz

In [12]:
colonnes_triees = sorted(df.columns, key=lambda col: df[col].nunique(), reverse=True)

for col in colonnes_triees:
    print(f"{col}: {df[col].nunique()}")

N° SERIE PC: 509
NOM RESEAU: 452
MAC ADRESSE ETHERNET: 445
N° SERIE ECRAN 1: 435
UTILISATEUR PRINCIPAL: 359
MAC ADRESSE WIFI: 184
DATE ACTIVATION: 183
CLEF OFFICE: 170
MODELE ECRAN 1: 141
EMPLACEMENT: 121
CLEF ACTIVATION: 110
DATE ACHAT PC: 93
N° BC PC: 86
Clé OS PC: 76
DATE FIN GARANTIE PC: 73
SERVICE: 69
PROCESSEUR PC: 66
MARQUE PC: 62
N° SERIE ECRAN 2: 59
DATE ACHAT ECRAN 1: 53
N° BC ECRAN 1: 48
DATE ACHAT OFFICE: 33
TYPE ECRAN 1: 33
VERSION OFFICE: 32
BC OFFICE: 31
MODELE ECRAN 2: 30
MARQUE ECRAN 1: 29
DATE FIN GARANTIE ECRAN 1: 26
TYPE: 24
N° BC ECRAN 2: 22
DATE ACHAT ECRAN 2: 22
Mail ACTIVATION: 18
Adresse IP PC: 17
OS: 15
FOURNISSEUR ECRAN 1: 14
WEBCAM: 13
N° CONTRAT OPEN MICROSOFT: 13
CASQUE: 12
TYPE ECRAN 2: 12
FOURNISSEUR PC: 11
RAM PC: 10
DATE FIN GARANTIE ECRAN 2: 10
MARQUE ECRAN 2: 9
FOURNISSEUR OFFICE: 8
FOURNISSEUR ECRAN 2: 7
TYPE LICENCE OFFICE: 6
TYPE ECRAN TELETRAVAIL: 6
eligible W10: 5
N° SERIE ECRAN TELETRAVAIL: 4
CLEF WIFI: 3
TYPE LICENCE PC: 3
TYPE ECRAN 3: 3
MARQUE ECRAN 3: 3
MODELE ECRAN 3: 3
N° SERIE ECRAN 3: 3
FOURNISSEUR ECRAN 3: 3
N° BC ECRAN 3: 3
MODELE ECRAN TELETRAVAIL: 3
ABSOLUTE DELL: 2
DATE ACHAT ECRAN 3: 2
DATE FIN GARANTIE ECRAN 3: 2
MARQUE ECRAN TELETRAVAIL: 2
FOURNISSEUR ECRAN TELETRAVAIL: 2
N° BC ECRAN TELETRAVAIL: 2
LECTEUR DVD/CD EXTERNE: 1
DATE ACHAT ECRAN TELETRAVAIL: 1
DATE FIN GARANTIE ECRAN TELETRAVAIL: 1
TYPE ECRAN TELETRAVAIL2: 1
MARQUE ECRAN TELETRAVAIL3: 1
MODELE ECRAN TELETRAVAIL4: 1
N° SERIE ECRAN TELETRAVAIL5: 1
FOURNISSEUR ECRAN TELETRAVAIL6: 1
N° BC ECRAN TELETRAVAIL7: 1
DATE ACHAT ECRAN TELETRAVAIL8: 1
DATE FIN GARANTIE ECRAN TELETRAVAIL2: 0

In [6]:
display(df)

,SERVICE,EMPLACEMENT,UTILISATEUR PRINCIPAL,NOM RESEAU,N° SERIE PC,CLEF WIFI,LECTEUR DVD/CD EXTERNE,WEBCAM,CASQUE,TYPE,...,DATE ACHAT ECRAN TELETRAVAIL,DATE FIN GARANTIE ECRAN TELETRAVAIL,TYPE ECRAN TELETRAVAIL2,MARQUE ECRAN TELETRAVAIL3,MODELE ECRAN TELETRAVAIL4,N° SERIE ECRAN TELETRAVAIL5,FOURNISSEUR ECRAN TELETRAVAIL6,N° BC ECRAN TELETRAVAIL7,DATE ACHAT ECRAN TELETRAVAIL8,DATE FIN GARANTIE ECRAN TELETRAVAIL2
0,?????????,?????????,None,None,None,None,None,None,None,ECRAN,...,None,None,None,None,None,None,NaN,None,None,None
1,?????????,?????????,None,None,None,None,None,None,None,ECRAN,...,None,None,None,None,None,None,NaN,None,None,None
2,?????????,?????????,None,None,None,None,None,None,None,ECRAN,...,None,None,None,None,None,None,NaN,None,None,None
3,?????????,?????????,None,None,None,None,None,None,None,ECRAN,...,None,None,None,None,None,None,NaN,None,None,None
4,?????????,?????????,None,None,None,None,None,None,None,ECRAN,...,None,None,None,None,None,None,NaN,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
665,STOCK PC,DSI,None,None,JN22WF4,None,None,None,None,PC PORTABLE,...,None,None,None,None,None,None,NaN,None,None,None
666,STOCK PC,DSI,None,None,FN22WF4,None,None,None,None,PC PORTABLE,...,None,None,None,None,None,None,NaN,None,None,None
667,STOCK PC,DSI,None,None,HN22WF4,None,None,None,None,PC PORTABLE,...,None,None,None,None,None,None,NaN,None,None,None
668,STOCK PC,DSI,None,None,H4W1WF4,None,None,None,None,PC PORTABLE,...,None,None,None,None,None,None,NaN,None,None,None
669,STOCK PC,DSI,None,None,G4W1WF4,None,None,None,None,PC PORTABLE,...,None,None,None,None,None,None,NaN,None,None,None